services:

  first:
    build:
      context: ../Part5
    image: image_nginx:v5
    volumes:
      - ${PWD}/../Part5/nginx:/etc/nginx
    # bind mount: путь на хосте -> путь в контейнере
    networks:
      - app_network

  second:
    image: nginx
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network
    ports:
      - 80:8080

networks:
  app_network:  # Defining a custom network
